### ISSUE TITLE
Bhaava Ayurveda - Changes to be done on priority

### ISSUE THREAD

**Issue by keertihegde** [Avadhuta-Technologies/Bhaava-Ayurveda#16]
Header issue : 
   - [x] Logo should be updated properly
   - [x]  In wellness menu, background image to be changed with other suitable images.
   - [x] In wellness menu, the border of all menus should be consistant
   - [x] Change blog to blogs
   - [x] Wellness menu CTA button style should be changed.

Home page : 
   - [x]  In banner, the slider arrow color to be changed
   - [x] 2nd banner buddha image to be changed and replaced with suitable image - https://github.com/Avadhuta-Technologies/Bhaava-Ayurveda/issues/7
   - [x] 3rd banner image, title, subtitle
   - [x] Banner button style should be changed
   - [x] Banner CTA button should be navigate to respective pages
   - [x] Banner image height should be adjusted so that text should align center
   - [x] Padding/Margin top and bottom should be added to Wellness journey section
   - [ ] Products details informations - https://github.com/Avadhuta-Technologies/Bhaava-Ayurveda/issues/14
   - [x]  Doctors content - https://github.com/Avadhuta-Technologies/Bhaava-Ayurveda/issues/14
   - [x] Bottom banner to be replaced
   - [x] Testimonial text description should be left aligned
   - [x] Bottom banner text and button should be left aligned

Swarnamruthaprasana : 
   - [x] 2nd section baby image should be changed  - https://github.com/Avadhuta-Technologies/Bhaava-Ayurveda/issues/17
   - [x] 2nd section padding top to be removed
   - [x] Bottom CTA button background image to be changed - https://github.com/Avadhuta-Technologies/Bhaava-Ayurveda/issues/17
   - [x] Bottom banner text and button should be left aligned

Autism : 
   - [x] 2nd section image should be replaced
   - [x] 3rd section background image to be changed
   - [x] Bottom CTA button background image to be changed
   - [x] Bottom banner text and button should be left aligned

Treatments : 
   - [x] Reduce the padding/margin top in the 2nd section
   - [x] Treatments images should be replced with suitable icon
   - [x] Bottom CTA button background image to be changed
   - [x] Bottom banner text and button should be left aligned

Panchakarma :
   - [x] Banner image should be modified, so that text will not get overlap with the images
   - [x] 3rd section images to be replaced with suitable icons
   - [x] 4th section images to be replaced with suitable icons
   - [x] 5th section CTA button style should be changed
   - [x] Tailored for your well-being section card hover style should be changed
   - [x] Bottom CTA button background image to be changed
   - [x] Bottom banner text and button should be left aligned
  
Our Journey :
   - [x] Images at the bottom of our journey page to be replaced/removed
   - [x] Bottom CTA button style to be chnaged
   - [x] Gallery images to be updated - https://github.com/Avadhuta-Technologies/Bhaava-Ayurveda/issues/14
   - [x] Bottom banner text and button should be left aligned

Visit Us : 
   - [x] Address at the bottom should align properly
   - [x] Contact us form CTA button style to be updated
   - [x] Bottom banner text and button should be left aligned

Footer :
   - [x] Design to be changed

  Common changes : 
   - [x] All the buttons font size changed to 14px and change uppercase to lowercase
   - [x] Check the content spellings and grammer
